using LibraryAPI.Models;
using LibraryAPI.Services;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace LibraryAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AIAssistantController : Controller
    {
        private readonly AIAssistantHelper _aIAssistantHelper;

        public AIAssistantController(AIAssistantHelper aIAssistantHelper)
        {
            _aIAssistantHelper = aIAssistantHelper;
        }

        /// <summary>
        /// Generates an AI response based on the provided prompt.
        /// </summary>
        /// <param name="prompt">The user's input for AI processing.</param>
        /// <returns>Generated AI content as plain text.</returns>
        [HttpGet("prompt")]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(typeof(string), StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<string>> GetAIRequest([Required] string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
                return BadRequest("Prompt cannot be empty.");

            var result = await _aIAssistantHelper.GenerateContentAsync(prompt);
            return Ok(result);
        }

        /// <summary>
        /// Generates and returns a book with detailed information using AI.
        /// </summary>
        /// <param name="prompt">AI query to generate or search for a book.</param>
        /// <returns>Book details object generated by AI.</returns>
        [HttpGet("getBook")]
        [ProducesResponseType(typeof(BookWithDetailsDto), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(typeof(string), StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<BookWithDetailsDto>> GetBookByAI([Required] string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
                return BadRequest("Prompt cannot be empty.");

            var book = await _aIAssistantHelper.GenerateBookWithDetailsAsync(prompt);
            return Ok(book);
        }
    }
}
