using LibraryAPI.Models;
using LibraryAPI.Services;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace LibraryAPI.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class AIAssistantController : Controller
    {
        private readonly AIAssistantHelper _aIAssistantHelper;

        public AIAssistantController(AIAssistantHelper aIAssistantHelper)
        {
            _aIAssistantHelper = aIAssistantHelper;
        }

        /// <summary>
        /// Generates an AI response based on the provided prompt.
        /// </summary>
        /// <param name="prompt">The user's input for AI processing.</param>
        /// <returns>Generated AI content as plain text.</returns>
        [HttpGet("prompt")]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(typeof(string), StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<string>> GetAIRequest([Required] string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
                return BadRequest("Prompt cannot be empty.");

            var result = await _aIAssistantHelper.GenerateContentAsync(prompt);
            return Ok(result);
        }

        /// <summary>
        /// Generates and returns a book with detailed information using AI.
        /// </summary>
        /// <param name="prompt">AI query to generate or search for a book.</param>
        /// <returns>Book details object generated by AI.</returns>
        [HttpGet("getBook")]
        [ProducesResponseType(typeof(BookWithDetailsDto), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(typeof(string), StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<BookWithDetailsDto>> GetBookByAI([Required] string prompt)
        {
            if (string.IsNullOrWhiteSpace(prompt))
                return BadRequest("Prompt cannot be empty.");

            var book = await _aIAssistantHelper.GenerateBookWithDetailsAsync(prompt);
            return Ok(book);
        }

        /// <summary>
        /// Improves the writing quality of provided text using AI suggestions.
        /// </summary>
        /// <param name="prompt">The text to improve.</param>
        /// <param name="context">Optional context (e.g., "review comment", "chat message").</param>
        /// <returns>Improved version of the text.</returns>
        [HttpGet("improve-text")]
        [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(typeof(string), StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<string>> ImproveText([Required] string prompt, string? context = null)
        {
            if (string.IsNullOrWhiteSpace(prompt))
                return BadRequest("Text cannot be empty.");

            var improvedText = await _aIAssistantHelper.ImproveTextAsync(prompt, context);
            return Ok(improvedText);
        }

        /// <summary>
        /// Generates quick reply suggestions based on conversation context.
        /// </summary>
        /// <param name="prompt">The conversation context or initial message.</param>
        /// <param name="count">The number of quick replies to generate (1-10, default: 5).</param>
        /// <returns>Array of suggested quick replies.</returns>
        [HttpGet("quick-replies")]
        [ProducesResponseType(typeof(string[]), StatusCodes.Status200OK)]
        [ProducesResponseType(typeof(string), StatusCodes.Status400BadRequest)]
        [ProducesResponseType(typeof(string), StatusCodes.Status500InternalServerError)]
        public async Task<ActionResult<string[]>> GetQuickReplies([Required] string prompt, [FromQuery] int count = 5)
        {
            if (string.IsNullOrWhiteSpace(prompt))
                return BadRequest("Prompt cannot be empty.");

            if (count <= 0 || count > 10)
                return BadRequest("Count must be between 1 and 10.");

            var replies = await _aIAssistantHelper.GenerateQuickRepliesAsync(prompt, count);
            return Ok(replies);
        }
    }
}
